/* BOLUM B: sahne HTML + gokyuzu */
(function(){'use strict';var D=window.__dny3;if(!D)return;var EN=D.EN;
var sahne=document.createElement('div');sahne.className='dny3-sahne';sahne.id='dny3Sahne';
sahne.style.setProperty('--dny-vurgu',D.vurgu);sahne.style.setProperty('--dny-parlama',D.parlama);
var h='';
h+='<canvas class="dny3-gokyuzu" id="dny3Sky"></canvas><div class="dny3-icerik">';
h+='<div class="dny3-ilerleme" id="dny3Bar"><i></i><i></i><i></i><i></i></div>';
h+='<section class="dny3-adim" data-adim="1"><div class="dny3-adim-kart"><div class="dny3-havai-baslik">';
h+='<span class="dny3-adim-no">'+(EN?'Step 1/4 Fireworks':'Adim 1/4 Havai Fisekler')+'</span>';
h+='<h1 class="dny3-isim">'+D.kelimele(D.isimGoster,0.35)+'</h1>';
h+='<div class="dny3-kutlama">'+D.kelimele(D.kutlama,0.9)+'</div>';
h+='<div class="dny3-alt-not">'+D.esc(D.NOT||(EN?'Made with love':'Sevgiyle hazirlandi'))+'</div>';
h+='<div class="dny3-kaydir-isaret"><span>'+(EN?'Scroll down':'Asagi kaydir')+'</span><span class="ok">v</span></div>';
h+='</div></div></section>';
h+='<section class="dny3-adim" data-adim="2"><div class="dny3-adim-kart">';
h+='<span class="dny3-adim-no">'+(EN?'Step 2/4 Message':'Adim 2/4 Kisisel Mesaj')+'</span>';
h+='<div class="dny3-mesaj-liste">'+D.dizeHtml+'</div>';
h+='<div class="dny3-kaydir-isaret"><span>'+(EN?'Keep scrolling':'Kaydirmaya devam et')+'</span><span class="ok">v</span></div>';
h+='</div></div></section>';
h+='<section class="dny3-adim" data-adim="3"><div class="dny3-adim-kart">';
h+='<span class="dny3-adim-no">'+(EN?'Step 3/4 Gift':'Adim 3/4 Hediye Zarfi')+'</span>';
h+='<div class="dny3-zarf" id="dny3Zarf" role="button" tabindex="0">';
h+='<div class="dny3-zarf-govde"><div class="dny3-zarf-kapak"></div>';
h+='<div class="dny3-zarf-mektup">Hediye zarfi: dokun ve ac</div>';
h+='<div class="dny3-zarf-muhur">+</div></div></div>';
h+='<div class="dny3-hediye-icerik" id="dny3Hediye"></div>';
h+='</div></div></section>';
h+='<section class="dny3-adim" data-adim="4"><div class="dny3-adim-kart"><div class="dny3-kapanis">';
h+='<span class="dny3-adim-no">'+(EN?'Step 4/4 Finale':'Adim 4/4 Final')+'</span>';
h+='<div class="buyuk">*</div>';
h+='<div class="dny3-kutlama">'+D.kelimele(EN?'Once more, happy birthday!':'Nice mutlu yaslara!',0.1)+'</div>';
h+='<button class="dny3-tekrar" id="dny3Tekrar" type="button">Tekrar Izle</button>';
h+='<a class="dny3-sablon-link" id="dny3SablonLink" href="#">Kart tasarimini gor</a>';
h+='</div></div></section></div>';
h+='<div class="dny3-altbar"><a href="index.html">Kart olustur</a></div>';
sahne.innerHTML=h;document.body.appendChild(sahne);document.body.style.overflow='hidden';
window.__dny3.sahne=sahne;
var sky=document.getElementById('dny3Sky'),sx=sky.getContext('2d');
function boy(){sky.width=innerWidth;sky.height=innerHeight;}boy();addEventListener('resize',boy);
window.__dny3.sky=sky;window.__dny3.sx=sx;window.__dny3.par=[];
})();
